api/urls.py
from django.urls import re_path
from django.views.decorators.csrf import csrf_exempt

from api.views import *


urlpatterns = [

	re_path("supervisor/((?P<pk>\d+)/)?", csrf_exempt(SupervisorView.as_view())),
	re_path("sede/((?P<pk>\d+)/)?", csrf_exempt(SedeView.as_view())),
	re_path("programa/((?P<pk>\d+)/)?", csrf_exempt(ProgramaView.as_view())),
	re_path("nte/((?P<pk>\d+)/)?", csrf_exempt(NTEView.as_view())),
	re_path("municipio/((?P<pk>\d+)/)?", csrf_exempt(MunicipioView.as_view())),
	re_path("faculdade/((?P<pk>\d+)/)?", csrf_exempt(FaculdadeView.as_view())),
	re_path("estagiario/((?P<pk>\d+)/)?", csrf_exempt(EstagiarioView.as_view())),
	re_path("edital/((?P<pk>\d+)/)?", csrf_exempt(EditalView.as_view())),
	re_path("curso/((?P<pk>\d+)/)?", csrf_exempt(CursoView.as_view())),
	re_path("sede_supervisor_estagiario/((?P<pk>\d+)/)?", csrf_exempt(EstagiarioView.as_view())),

]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token # <-- NEW

urlpatterns = [
    path('', include('home.home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_datta.urls')),
    path('', include('django_dyn_dt.urls')), # <-- NEW: Dynamic_DT Routing  
    path("", include("home.autenticacao.urls")),    # Auth routes - login / register
    path("", include("home.estagiario.urls")),
    path("", include("home.supervisor.urls")),
    path("", include("home.nte.urls")),
    path("", include("home.curso.urls")),
    path("", include("home.programa.urls")),
    path("", include("home.faculdade.urls")),
    path("", include("home.edital.urls")),
    path("", include("home.municipio.urls")),
    path("", include("home.sede.urls")),    
]

# Lazy-load on routing is needed
# During the first build, API is not yet generated
try:
    urlpatterns.append( path("api/"      , include("api.urls"))    )
    urlpatterns.append( path("login/jwt/", view=obtain_auth_token) )
except:
    pass

home/home/urls.py
from django.urls import path
from home.home import views as home_views

urlpatterns = [
    path("", home_views.index, name="home"),
    path("partiu-estagio/dashboard/", home_views.dashboard_estagiario_partiu_estagio, name="dashboard_estagiario_partiu_estagio"),
    path("estagiario/dashboard/", home_views.dashboard_estagiario_mais_futuro, name="dashboard_estagiario_mais_futuro"),
    path("supervisor/dashboard/", home_views.dashboard_supervisor, name="dashboard_supervisor"),
    path("nte/dashboard/", home_views.dashboard_nte, name="dashboard_nte"),
    path("curso/dashboard/", home_views.dashboard_curso, name="dashboard_curso"),
    path("programa/dashboard/", home_views.dashboard_programa, name="dashboard_programa"),
    path("faculdade/dashboard/", home_views.dashboard_faculdade, name="dashboard_faculdade"),
    path("edital/dashboard/", home_views.dashboard_edital, name="dashboard_edital"),
    path("municipio/dashboard/", home_views.dashboard_municipio, name="dashboard_municipio"),
    path("sede/dashboard/", home_views.dashboard_sede, name="dashboard_sede"),
]

home/nte/urls.py
from django.urls import path
from home.nte import views

urlpatterns = [
    # Consultar NTEs
    path("nte/", views.consultar_nte, name="consultar_nte"),

    # Adicionar novo NTE
    path("nte/adicionar/", views.criar_nte, name="adicionar_nte"),

    # Editar NTE por ID
    path("nte/editar/<str:id_NTE>", views.editar_nte, name="editar_nte"),
]

home/autenticacao/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models

# Create your models here.

home/curso/models.py
from django.db import models

class Curso(models.Model):
    id_curso =  models.AutoField(primary_key=True)
    nome_curso = models.CharField(max_length=50)
    
    class Meta:
        db_table = 'CUSO_curso'

    def __str__(self):
        return self.nome_curso

        
        

home/edital/models.py
from django.db import models

class Edital(models.Model):
    id_edital = models.CharField(primary_key=True, max_length=7)
    quantidade_vagas_edital = models.IntegerField()
    
    class Meta:
        db_table = 'EDTL_edital'

    def __str__(self):
        return self.id_edital


home/estagiario/models.py
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from cpf_field.models import CPFField
from ..supervisor.models import Supervisor
from ..faculdade.models import Faculdade
from ..sede.models import Sede
from ..programa.models import Programa
from ..curso.models import Curso


class Estagiario(models.Model):
    cpf_estagiario = CPFField(primary_key=True)
    nome_estagiario = models.CharField(max_length=100)
    rg_estagiario = models.CharField(max_length=12)
    turno_estagiario = models.CharField(max_length=10)
    email_estagiario = models.CharField(max_length=200)
    semestre_estagiario = models.IntegerField()
    nis_pis_estagiario = models.CharField(max_length=14)
    telefone_estagiario = models.CharField(max_length=15)
    nome_responsavel_estagiario = models.CharField(max_length=100)
    data_nascimento_estagiario = models.CharField(max_length=10)
    genero_estagiario = models.CharField(max_length=9)
    raca_estagiario = models.CharField(max_length=8)
    bairro_estagiario = models.CharField(max_length=36)
    numero_estagiario = models.CharField(max_length=6)
    complemento_estagiario = models.CharField(max_length=200)
    matricula_estagiario = models.CharField(max_length=8)
    situacao_estagiario = models.CharField(max_length=15)
    #FOREIGN KEY
    faculdade_estagiario = models.ForeignKey(Faculdade, on_delete=models.PROTECT, related_name="faculdade", null = True)
    programa_estagiario = models.ForeignKey(Programa, on_delete=models.PROTECT, related_name="programa", null = True)
    curso_estagiario = models.ForeignKey(Curso, on_delete=models.PROTECT, related_name="curso", null = True)
    
    class Meta:
        db_table = 'ESTA_estagiario'

    def __str__(self):
        return self.nome_estagiario


class Sede_Supervisor_Estagiario(models.Model):
    SSES_id = models.AutoField(primary_key=True)
    SSES_id_sede = models.ForeignKey(Sede, on_delete=models.PROTECT, related_name="SSES_id_sede", null = True)
    SSES_id_supervisor = models.ForeignKey(Supervisor, on_delete=models.PROTECT, related_name="SSES_id_supervisor", null = True)
    SSES_id_estagiario = models.ForeignKey(Estagiario, on_delete=models.PROTECT, related_name="SSES_id_estagiario", null = True)

    class Meta:
        db_table = 'SSES_sede_supervisor_estagiario'

home/municipio/models.py
from django.db import models
from ..nte.models import NTE

class Municipio(models.Model):
    id_municipio = models.AutoField(primary_key=True)
    nome_municipio = models.CharField(max_length=200)
    #foreign key
    id_nte_municipio = models.ForeignKey(NTE, on_delete=models.PROTECT, related_name="municipios")

    class Meta:
        db_table = 'MUNI_municipio'

    def __str__(self):
        return self.nome_municipio

home/programa/models.py
from django.db import models
from ..edital.models import Edital

class Programa(models.Model):
    id_programa = models.AutoField(primary_key=True)
    nome_programa = models.CharField(max_length=100)
    
    #FOREIGN KEY
    edital_estagiario = models.ForeignKey(Edital, on_delete=models.PROTECT, related_name="edital", null = True)

    class Meta:
        db_table = 'PROG_programa'

    def __str__(self):
        return self.nome_programa

home/autenticacao/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

home/curso/forms.py
from django import forms
from home.curso.models import Curso

class CursoForm(forms.ModelForm):
    nome_curso = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome do Curso",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    class Meta:
        model = Curso
        fields = "__all__"

home/edital/forms.py
from django import forms
from home.edital.models import Edital

class EditalForm(forms.ModelForm):
    id_edital = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Código do Edital",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )
    quantidade_vagas_edital = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Quantidade de Vagas",
                "class": "form-control mask-matricula",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    class Meta:
        model = Edital
        fields = "__all__"

home/estagiario/forms.py
from django import forms
from home.estagiario.models import Estagiario
from home.supervisor.models import Supervisor
from home.faculdade.models import Faculdade
from home.sede.models import Sede
from ..edital.models import Edital
from ..programa.models import Programa
from ..curso.models import Curso

class EstagiarioForm(forms.ModelForm):
    cpf_estagiario = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "CPF do Estagiário",
                "class": "form-control mask-cpf",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )
    # outros campos com as mesmas alterações...

    programa_estagiario = forms.ModelChoiceField(queryset=Programa.objects.all(), 
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    edital_estagiario = forms.ModelChoiceField(queryset=Edital.objects.all(), 
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    curso_estagiario = forms.ModelChoiceField(queryset=Curso.objects.all(), 
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    class Meta:
        model = Estagiario
        fields = "__all__"

home/faculdade/forms.py
from django import forms
from home.faculdade.models import Faculdade

class FaculdadeForm(forms.ModelForm):
    nome_faculdade = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome da Faculdade",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo Obrigatório')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )
    cnpj_faculdade = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "CNPJ da Faculdade",
                "class": "form-control mask-cnpj",
            }
        )
    )
    nome_direitor_faculdade = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome do Diretor da Faculdade",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo Obrigatório')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )
    telefone_faculdade = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Telefone da Faculdade",
                "class": "form-control mask-telefone",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo Obrigatório')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )
    campus_faculdade = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Campus da Faculdade",
                "class": "form-control",
            }
        )
    )

    class Meta:
        model = Faculdade
        fields = "__all__"

home/municipio/forms.py
from django import forms
from home.municipio.models import Municipio
from home.nte.models import NTE

class MunicipioForm(forms.ModelForm):
    requerido = "required oninvalid"
    campo_requerido = "this.setCustomValidity('Campo requerido')" 
    onchange = "onchange"
    campo_requerido_empty = "this.setCustomValidity('')"

    nome_municipio = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome do Município",
                "class": "form-control",
                requerido: campo_requerido,
                onchange: campo_requerido_empty
            }
        )
    )
    
    id_nte_municipio = forms.ModelChoiceField(
        queryset=NTE.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-control",
                requerido: campo_requerido,
                onchange: campo_requerido_empty
            }
        )
    )

    class Meta:
        model = Municipio
        fields = "__all__"

home/nte/forms.py
from django import forms
from home.nte.models import NTE

class NTEForm(forms.ModelForm):
    
    nome_direitor_NTE = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome do Diretor",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    telefone_NTE = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Telefone do NTE",
                "class": "form-control mask-telefone",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    email_NTE = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Email do NTE",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    class Meta:
        model = NTE
        fields = "__all__"

home/programa/forms.py
from django import forms
from home.programa.models import Programa

class ProgramaForm(forms.ModelForm):
    
    nome_programa = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nome do Programa",
                "class": "form-control",
                "required": True,
                "oninvalid": "this.setCustomValidity('Campo requerido')",
                "onchange": "this.setCustomValidity('')",
            }
        )
    )

    class Meta:
        model = Programa
        fields = "__all__"

templates/home/MFES_criar_estagiario.html
{% extends "layouts/base.html" %}

{% block title %} Partiu Estagio {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ Padrao do HEADER da pagina] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Estagiários Mais Futuro</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><span class="feather icon-home"></span></a></li>
                                <li class="breadcrumb-item"><a href="{% url 'dashboard_estagiario_mais_futuro' %}">DashBoard</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'criar_estagiario_mais_futuro' %}">Criar Estagiários</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [  Padrao do HEADER da pagina ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Cadastrar Estagiário </h5>
                                </div>
                                {% if mensagem %}
                                    {% if error %}
                                        <div class="alert alert-danger" role="alert">
                                            <button class="close" data-dismiss="alert">&times;</button>
                                            <p>{{ mensagem }}</p>
                                        </div>
                                    {% else %}
                                        <div class="alert alert-success" role="alert">
                                            <button class="close" data-dismiss="alert">&times;</button>
                                            <p>{{ mensagem }}</p>
                                        </div>
                                    {% endif %}
                                {% endif %}
                                <div class="col-md-6">
                                    <form role="form" method="POST" action="" >
                                        {% csrf_token %}
                                        
                                        <label>Nome do Estagiário<b>*</b> </label>
                                        <div>{{ form.nome_estagiario }}</div>
                                        <div id="linhaForms"> 
                                            <div class="unidade">
                                                <label>CPF do Estagiário<b>*</b> </label>
                                                <div>{{ form.cpf_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>RG do Estagiário<b>*</b> </label>
                                                <div>{{ form.rg_estagiario }}</div>
                                            </div>
                                            <div class="unidade">
                                                <label>NIS do Estagiário </label>
                                                <div>{{ form.nis_pis_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>Data de nascimento do Estagiário </label>
                                                <div>{{ form.data_nascimento_estagiario }}</div>
                                            </div>
                                        </div>
                                            
                                        <label>Email do Estagiário<b>*</b> </label>
                                        <div>{{ form.email_estagiario }}</div>
                                            
                                        <div id="linhaForms">
                                            <div>
                                                <label>Telefone do Estagiário<b>*</b> </label>
                                                <div>{{ form.telefone_estagiario }}</div>
                                            </div>
                                        </div>

                                        <div id="linhaForms">
                                            <div class="unidade">
                                                <label>Gênero do Estagiário<b>*</b> </label>
                                                <div>{{ form.genero_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>Raça do Estagiário<b>*</b> </label>
                                             <div>{{ form.raca_estagiario }}</div>
                                            </div>    
                                        </div>

                                        <label>Responsável pelo Estagiário<b>*</b> </label>
                                        <div>{{ form.nome_responsavel_estagiario }}</div>

                                        <div id="linhaForms">
                                            <div class="unidade">
                                                <label>Bairro<b>*</b></label>
                                                <div>{{ form.bairro_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>Número<b>*</b></label>
                                                <div>{{ form.numero_estagiario }}</div>
                                            </div>
                                        </div>
                                            
                                        <label>Complemento</label>
                                        <div>{{ form.complemento_estagiario }}</div>
                                        
                                        <label>Faculdade do Estagiário<b>*</b> </label>
                                        <div>{{ form.faculdade_estagiario }}</div>

                                        <div id="linhaForms">
                                            <div class="unidade">
                                                <label>Semestre do Estagiário<b>*</b> </label>
                                                <div>{{ form.semestre_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>Matrícula do Estagiário  </label>
                                                <div>{{ form.matricula_estagiario }}</div>
                                            </div>
                                            
                                            <div class="unidade">
                                                <label>Turno do Estagiário<b>*</b> </label>
                                                <div>{{ form.turno_estagiario }}</div>
                                            </div>
                                            <div>
                                                <label>Situação do Estagiário<b>*</b> </label>
                                                <div>{{ form.situacao_estagiario }}</div>
                                            </div>
                                        </div>

                                        <label>Supervisor do Estagiário<b>*</b> </label>
                                        <div>{{ form.supervisor_estagiario }}</div>

                                        <div id="linhaForms">
                                            <div class="unidade">
                                                <label>Sede do Estagiário<b>*</b></label>
                                                <div>{{ form.sede_estagiario }}</div>
                                            </div> 
                                            <div>
                                                <label>Curso do Estagiário<b>*</b></label>
                                                <div>{{ form.curso_estagiario }}</div>
                                            </div>
                                        </div>
                                        <div id="linhaForms">
                                            <div class="unidade">
                                                <label>Programa do Estagiário<b>*</b></label>
                                                <div>{{ form.programa_estagiario }}</div>
                                            </div> 
                                            <div>
                                                <label>Edital do Estagiário<b>*</b></label>
                                                <div>{{ form.edital_estagiario }}</div>
                                            </div>
                                        </div>
                                        
                                        <div  class="card"></div>
                                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script src="/static/assets/js/pages/mask.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="></script>

    <script>
        $(document).ready(function() {
            $('#id_turno_estagiario').select2();
            $('#id_semestre_estagiario').select2();
            $('#id_genero_estagiario').select2();
            $('#id_raca_estagiario').select2();
            $('#id_situacao_estagiario').select2();
            $('#id_supervisor_estagiario').select2();
            $('#id_sede_estagiario').select2();
            $('#id_faculdade_estagiario').select2();
            $('#id_curso_estagiario').select2();
            $('#id_programa_estagiario').select2();
            $('#id_edital_estagiario').select2();
        });
    </script>
{% endblock javascripts %}



templates/home/MUNI_grafico.html
{% extends "layouts/base.html" %}

{% block title %} Dados Gráficos {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

    <link rel="stylesheet" href="/static/assets/plugins/chart-morris/css/morris.css">

{% endblock stylesheets %}

{% block content %}

{% include 'grafico/MUNI_grafico_geral.html' %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Dados</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Gráficos Municípios</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Morris Chart ] start -->
                    <div class="col-xl-6">
                        <div class="card">
                            <div class="card-header">
                                <h5>NTE</h5>
                            </div>
                            <div id="chart-nte"></div>
                        </div>
                    </div>
                    <!-- [ Morris Chart ] end -->
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}